name: zero_waste_iot_app
description: "A new Flutter project."

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  bloc: ^8.1.4
  camera: ^0.11.0+1
  dio: ^5.4.3+1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_svg: ^2.0.10+1
  flutter_zxing: ^1.7.0
  image: ^4.2.0
  smooth_page_indicator: ^1.1.0
  tflite_flutter: ^0.10.4
  tflite_v2: ^1.0.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/ml/
    - assets/model.tflite
    - assets/labels.txt
fonts:
  - family: Outfit
    fonts:
      - asset: assets/fonts/Outfit/Outfit-Black.ttf
        weight: 900
      - asset: assets/fonts/Outfit/Outfit-Bold.ttf
        weight: 700
      - asset: assets/fonts/Outfit/Outfit-ExtraBold.ttf
        weight: 800
      - asset: assets/fonts/Outfit/Outfit-ExtraLight.ttf
        weight: 200
      - asset: assets/fonts/Outfit/Outfit-Light.ttf
        weight: 300
      - asset: assets/fonts/Outfit/Outfit-Medium.ttf
        weight: 500
      - asset: assets/fonts/Outfit/Outfit-Regular.ttf
        weight: 400
      - asset: assets/fonts/Outfit/Outfit-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/Outfit/Outfit-Thin.ttf
        weight: 100

flutter_assets:
  assets_path: assets/images/
  output_path: lib/shared/
  filename: assets.dart
  field_prefix: null
